// PLACEHOLDER — not a real Firebase project yet.
//
// This feature (Play Integrity / App Attest via Firebase App Check, for the
// document-conversion endpoint) needs a real Firebase project before it can
// work: create one, register the Android app (hu.wirinungarn.forditva) and
// iOS app (hu.wirinungarn.forditva3), enable App Check with the Play
// Integrity provider (Android) and App Attest provider (iOS), then replace
// the values below with the real ones from Project Settings > General, and
// enable Play Integrity in the linked Google Cloud project's API library.
//
// This file intentionally avoids google-services.json / GoogleService-Info.plist
// (which would require the Android Gradle plugin wired in, breaking CI until
// a real project exists) — FirebaseOptions are passed programmatically
// instead, so the app compiles and builds normally either way. Once real
// values are in place here, App Check activates automatically (see main.dart).
//
// Normally this file is generated by running `flutterfire configure`; doing
// that once the project exists will replace this placeholder correctly.
library;

import 'package:firebase_core/firebase_core.dart';
import 'dart:io' show Platform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isIOS) return ios;
    return android;
  }

  static const android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
  );

  static const ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    iosBundleId: 'hu.wirinungarn.forditva3',
  );
}
